env:
  browser: true
  es2020: true
  node: true
extends:
  - 'plugin:react/recommended'
  - airbnb-typescript
  - airbnb/hooks
  - plugin:import/typescript
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  sourceType: module
  project: tsconfig.json
plugins:
  - react
  - '@typescript-eslint'
  - 'react-hooks'
rules:
  react/jsx-filename-extension:
    - 1
    - extensions:
      - ".tsx"
  import/no-extraneous-dependencies: 0
  import/extensions:
    - error
    - ignorePackages
    - js: never
      jsx: never
      ts: never
      tsx: never
  import/prefer-default-export: 0
  react/require-default-props: 0
